# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
securityContext:
  sysctls:
    #kubernetes >= v1.11 and kernel version >= 4.15 needed
    #- name: kernel.msgmax
    #  value: "65536"
    - name: net.ipv4.tcp_syncookies
      value: "0"
    - name: net.ipv4.ip_local_port_range
      value: "1024 65535"
    - name: net.core.somaxconn
      value: "65535"
    - name: net.ipv4.ip_unprivileged_port_start
      value: "0"
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.tcp_fin_timeout
      value: "30"
    - name: net.ipv4.tcp_keepalive_intvl
      value: "10"
    - name: net.ipv4.tcp_keepalive_probes
      value: "2"
    - name: net.ipv4.tcp_keepalive_time
      value: "120"
    - name: net.ipv4.tcp_ecn
      value: "1"
    - name: net.ipv4.tcp_max_syn_backlog
      value: "65536"
    - name: net.ipv4.tcp_rfc1337
      value: "1"
    - name: net.ipv4.tcp_slow_start_after_idle
      value: "0"
    - name: net.ipv4.tcp_fack
      value: "1"
    - name: net.ipv4.tcp_max_tw_buckets
      value: "262144"
    - name: net.ipv4.tcp_fastopen
      value: "3"
    - name: net.ipv4.icmp_ratelimit
      value: "100"
    - name: net.ipv4.tcp_abort_on_overflow
      value: "1"
    - name: net.ipv4.tcp_adv_win_scale
      value: "2"
    - name: net.ipv4.tcp_retries2
      value: "8"
    - name: net.ipv4.tcp_syn_retries
      value: "3"
    - name: net.ipv4.tcp_synack_retries
      value: "2"
    - name: net.unix.max_dgram_qlen
      value: "512"
    - name: net.ipv4.tcp_fwmark_accept
      value: "1"
    - name: net.ipv4.fwmark_reflect
      value: "1"
env: []
resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
#水平自动伸缩
hpaCPU:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
